AllCops:
  TargetRubyVersion: 3.4.4
  Exclude:
    - "spec/**/*"
    - "vendor/**"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
